kind: pipeline
name: default
steps:
- name: ssh
  pull: true
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_username
    key: 
      from_secret: ssh_key
    port: 
      from_secret: ssh_port
    script:
      - echo "hello"
      -  php artisan deploy --hosts=drone-deploy.webfsd.com -s upload -vvv

