pipeline:
  ssh:
    image: appleboy/drone-ssh
    settings:
      host: drone-deploy.webfsd.com
      username: deployer
      password: 1234
      port: 32
      script:
        - echo hello
        - echo world
