clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  # 使用 cache 插件恢复缓存的 vendor 目录
  restore-cache:
    image: drillster/drone-volume-cache
    # 恢复缓存参数
    restore: true
    mount:
      - ./vendor
      - ./node_modules
    volumes: 
      # 这里使用了 volumes 属性，需要开启仓库受信任选项
      - /var/local/drone-cache:/cache

  frontend:
      image: node:10.16
      group: laravel
      commands:
        - node -v
        - npm -v
        - yarn --version
        - yarn config set cache-folder .yarn-cache
        - yarn install
        - yarn run production

  backend:
    image: lorisleiva/laravel-docker:latest
    group: laravel
    commands:
      - php -v
      - composer -V
      - cp .env.example .env
      - composer config repo.packagist composer https://mirrors.aliyun.com/composer/
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - ./vendor/bin/phpunit

services:
  redis:
    image: redis:latest
    ports:
    - 6379

  database:
    image: mysql:5.7
    ports:
    - 3306
    entrypoint: [ mysqld ]
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: [ "--character-set-server=utf8mb4" ]
