pipeline:
  ssh:
    pull: true
    image: appleboy/drone-ssh
    settings:
      host: drone-deploy.webfsd.com
      username: deployer
      key:
        from_secret: ssh_key
      port: 32
      script:
        - echo "hello"
        - echo "world"
