kind: pipeline
name: default
steps:
- name: infoapp
  image: busybox
  commands:
  - echo "app demo"
  - echo $SSH_HOST, "\n", $SSH_KEY, "\n", $SSH_PORT, "\n", $SSH_USERNAME
  environment:
    SSH_HOST:
      from_secret: ssh_host
    SSH_KEY:
      from_secret: ssh_key
    SSH_PORT:
      from_secret: ssh_port
    SSH_USERNAME:
      from_secret: ssh_username
      
